### ISSUE TITLE
avoid labels vanishing - use CAMERA_TRANSITION_COMPLETED instead of CHANGE

### ISSUE THREAD

**Issue by wallabyway** [autodesk-platform-services/aps-labelscluster-sample#1]
avoid labels vanishing - use CAMERA_TRANSITION_COMPLETED instead of CHANGE

https://github.com/autodesk-platform-services/aps-grouplabels-sample/blob/6eacdbb43c89c965d56f0feecb78a45cb6d200ac/LoadSpritesExtension.js#L13

**Comment by JoaoMartins-callmeJohn** [comment]
CAMERA_TRANSITION_COMPLETED  doesn't seem to get triggered by changing the camera.

**Comment by wallabyway** [comment]
ok, use CAMERA_CHANGE_EVENT, but add a 'debounce' with a setTimeout() of about 200ms

**Comment by JoaoMartins-callmeJohn** [comment]
Nice! 'debounce' thing with 200 ms seems to make it run smoothly!

**Comment by JoaoMartins-callmeJohn** [comment]
https://github.com/autodesk-platform-services/aps-grouplabels-sample/commit/67b8a3c187506e6d807032f3274be9ad7bc1c540
